AUTOGEN_HEADER = """
// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by modgen.py - Changes will be overwritten on next generation
// ============================================================================
"""

JSON_AUTOGEN_COMMENT = "⚠ AUTO-GENERATED - DO NOT EDIT - Changes will be overwritten"
